### PR TITLE
made all headers primary color (blue)

### PR DESCRIPTION
**Pull request by MavOmidK**

### CODE REVIEW

**Review by LeontiBrechko — APPROVED** [review]

**Comment by aagavin** [comment]
Hmm blue?

**Comment by aagavin** [comment]
@MavOmidK is there a way to do it in CSS?

**Comment by MavOmidK** [comment]
no idea, i tried with traditional css methods but it wasn't biting.

**Review by antonybogun — APPROVED** [review]
Blue stuff!

**Pull request merged**
