### PR TITLE
Feature/notifications

### PR DESCRIPTION
**Pull request by aagavin**
Added ability to send firebase user id to push notification service

### CODE REVIEW

**Review by antonybogun — APPROVED** [review]
Looks good to me

**Review by eddieysong — COMMENTED** [review]
Is there anyway to test without emulating? I can't get a decent emulation going (my Genymotion isn't playing well with `ionic run android`).

**Comment by aagavin** [comment]
@eddieysong you can test on your physical phone. If you run `ionic run android` with your phone plugged in it will run on your phone if you enable the developer options

**Comment by eddieysong** [comment]
I will get to it when the tutorial is empty.. which might not happen until
the end of my shift LOL

**Pull request merged**
